Algoritmo "ex03"

Var
media, nota1, nota2, nota3, nota4: real


Inicio
      escreva("Digite a primeria nota: ")
      leia(nota1)
      escreva("Digite a segunda nota: ")
      leia(nota2)
      escreva("Digite a terceira nota: ")
      leia(nota3)
      escreva("Digite a quarta nota: ")
      leia(nota4)
      
      media <- (nota1 + nota2 + nota3 + nota4) / 4

      escreva("A média aritimética de",nota1,",",nota2,",",nota3," e",nota4," é:",media)


Fimalgoritmo