Algoritmo "ex2"
//Problema é: ler o nome de uma pessoa, a sua idade e o seu salário e
//mostrar as informações
Var
nome: caractere
idade: inteiro
salario: real

Inicio
      escreva("Digite seu nome: ")
      leia(nome)
      limpatela
      escreva("Digite sua idade: ")
      leia(idade)
      limpatela
      escreva("Digite seu salário: ")
      leia(salario)
      limpatela
      escreva("Seu nome é ",nome,", sua idade é",idade," e seu salário é",salario)
Fimalgoritmo